global:
  # this is the repository that we try to authenticate upon
  # Can be any aws ecr related repository or other docker based repositories
  # ex. 123456789123.dkr.ecr.eu-west-2.amazonaws.com
  registry: ""
  # Provide an existing secret that hold registry credentials
  secretConfigName: global-secret
  registryUsername: ""
  registryPassword: ""
  image:
    registry: docker.io
    repository: vaggeliskls/aws-kubectl
    tag: latest

# Dynamic selection of registry type
docker:
  enabled: false
  secretConfigUsernameKey: "REGISTRY_USERNAME"
  secretConfigPasswordKey: "REGISTRY_PASSWORD"

aws-ecr:
  enabled: true
  schedule: "0 */8 * * *" # every 8 hours
  secretConfigUsernameKey: "REGISTRY_USERNAME"
  secretConfigPasswordKey: "REGISTRY_PASSWORD"
