apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-registry-auth-service-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: k8s-registry-auth-secret-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-registry-auth-secret-manager-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: k8s-registry-auth-service-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: k8s-registry-auth-secret-manager
  apiGroup: rbac.authorization.k8s.io
