name: REGISTRY AUTH CI

on:
  release:
    types: [published]

env:
  TAG_NAME: ${{ github.ref_name }}

jobs:
  oci-publish:
    name: OCI Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Install helm
        uses: azure/setup-helm@v4.2.0

      - name: 📦 Upload oci to docker.io
        env:
          OCI_IMAGE_NAME: k8s-registry-auth
        run: |
          echo ${{ secrets.DOCKER_REGISTRY_PASSWORD }} | helm registry login registry-1.docker.io -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin
          helm package ./
          helm push ${OCI_IMAGE_NAME}-${{env.TAG_NAME}}.tgz oci://registry-1.docker.io/${{ secrets.DOCKER_REGISTRY_USERNAME }}
        shell: bash
