name: REGISTRY AUTH CI

on:
  release:
    types: [published]

env:
  TAG_NAME: ${{ github.ref_name }}
  IMAGE_URL: docker.io/${{ github.actor }}/aws-kubectl

jobs:
  aws-kubectl:
    name: AWS KUBECTL publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: 📦 Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{env.IMAGE_URL}}:${{env.TAG_NAME}}
            ${{env.IMAGE_URL}}:latest
          platforms: linux/amd64,linux/arm64
          sbom: true
          provenance: true

  oci-publish:
    name: OCI Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Install helm
        uses: azure/setup-helm@v4.2.0

      - name: 📦 Upload oci to docker.io
        env:
          OCI_IMAGE_NAME: k8s-registry-auth
        run: |
          echo ${{ secrets.DOCKER_REGISTRY_PASSWORD }} | helm registry login registry-1.docker.io -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin
          helm package ./
          helm push ${OCI_IMAGE_NAME}-${{env.TAG_NAME}}.tgz oci://registry-1.docker.io/${{ secrets.DOCKER_REGISTRY_USERNAME }}
        shell: bash
